######################## default configuration ####################
baseURL = "https://corseio.netlify.app/"
languageCode = "en-us"
title = "Corse.io | Le spécialiste du référencement naturel en Corse"
theme = "gosaas-hugo"

############################# Plugins ##############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "plugins/slick/slick.css"
  [[params.plugins.css]]
  URL = "plugins/themify-icons/themify-icons.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  URL = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "plugins/slick/slick.min.js"

  
############################## navigation ###############################
[menu]
    
  [[menu.main]]
  name = "À propos"
  URL = "propos"
  weight = 2
  
  [[menu.main]]
  name = "Service"
  URL = "service"
  weight = 3
  
  [[menu.main]]
  name = "Portfolio"
  URL = "portfolio"
  weight = 4
  
  [[menu.main]]
  name = "Tarif"
  URL = "pricing"
  weight = 5
    
  [[menu.main]]
  name = "Contact"
  URL = "contact"
  weight = 6
  
  ###################### footer menu
  [[menu.footer]]
  name = "À propos"
  URL = "propos"
  weight = 2
  
  [[menu.footer]]
  name = "Service"
  URL = "service"
  weight = 3
  
  [[menu.footer]]
  name = "Portfolio"
  URL = "portfolio"
  weight = 4
  
  [[menu.footer]]
  name = "Tarif"
  URL = "pricing"
  weight = 5
    
  [[menu.footer]]
  name = "Contact"
  URL = "contact"
  weight = 6


#################### default parameters ################################
[params]
logo = "images/logo.png"
home = "Accueil"
# Meta data
description = "Référencement naturel pour une stratégie SEO efficace, analyse du site et partenariat pour augmenter sa visibilité."
author = "Corse.io"
# Google Analitycs
googleAnalitycsID = ""
# copyright
copyright = "| @2022 [Corse.io] Tout droit réservés  |"

  # Preloader
  [params.preloader]
  enable = true
  preloader = "" # use .png , .svg or .gif format

  # Navigation get start button
  [params.navButton]
  enable = true
  label = "Avoir un conseil"
  link = "contact"


############################### social links ############################
#[[params.social]]
#name = "Facebook"
#link = "#"

#[[params.social]]
#name = "Twitter"
#link = "#"

[[params.social]]
name = "Github"
link = "https://github.com/Fiurino666"

[[params.social]]
name = "Linkedin"
link = "https://www.linkedin.com/in/florian-favre-737013155/"


########################### footer call to action #####################
[params.cta]
enable = true
title  = "Rejoignez les sites qui performent et accélèrent leurs croissances, <br> utilisez Corse.io pour aller plus vite"
#button
label = "Démarrez avec nous"
link = "contact"


############################ footer ##############################
[params.footer]
bgImage = "images/backgrounds/footer-bg.png"
content = "Nos efforts sont votre augmentation de visibilité et de revenu."

# card we accept
#[[params.footer.card]]
#image = "images/paypal.png"
#[[params.footer.card]]
#image = "images/visa.png"
#[[params.footer.card]]
#image = "images/a-express.png"